"use client";
import { useState } from "react";

export default function LegalPage() {
  const [lang, setLang] = useState<"en" | "es">("en");
  const isEs = lang === "es";

  return (
    <main className="min-h-screen bg-[#080b12] text-[#f0f2f7] font-sans">

      {/* Header */}
      <header className="border-b border-white/[0.07] bg-[rgba(8,11,18,0.95)] sticky top-0 z-40 backdrop-blur-md">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2 text-sm font-bold text-white hover:text-[#4f7cff] transition-colors">
            ← ScoreMotive
          </a>
          <div className="flex items-center gap-3">
            <span className="text-xs text-[#8892a4]">{isEs ? "Legal y Privacidad" : "Legal & Privacy"}</span>
            <button onClick={() => setLang(lang === "en" ? "es" : "en")} className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-xs px-3 py-1.5 rounded-xl transition font-bold text-slate-300">
              🌐 {lang === "en" ? "ES" : "EN"}
            </button>
          </div>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-6 py-16">

        {/* Title */}
        <div className="mb-12">
          <span className="text-[11px] uppercase tracking-[3px] text-[#4f7cff] font-medium">Legal</span>
          <h1 className="text-4xl font-black tracking-[-1px] mt-2 mb-4">
            {isEs ? "Legal y Política de Privacidad" : "Legal & Privacy Policy"}
          </h1>
          <p className="text-[#8892a4] text-sm">{isEs ? "Última actualización: Junio 2026" : "Last updated: June 2026"}</p>
        </div>

        <div className="space-y-12">

          {/* Disclaimer */}
          <section className="bg-[rgba(245,158,11,0.05)] border border-[rgba(245,158,11,0.15)] rounded-2xl p-8">
            <h2 className="text-xl font-bold text-[#f59e0b] mb-4">
              ⚠️ {isEs ? "Descargo de Responsabilidad Educativa" : "Educational Disclaimer"}
            </h2>
            <div className="space-y-4 text-sm text-[#8892a4] leading-relaxed">
              {isEs ? (
                <>
                  <p>ScoreMotive es una herramienta educativa e informativa diseñada para ayudar a los usuarios a comprender conceptos financieros básicos como la puntuación de crédito FICO y las estrategias de manejo de deudas.</p>
                  <p><strong className="text-[#f0f2f7]">La información proporcionada por esta aplicación NO constituye asesoría financiera, legal ni fiscal profesional.</strong> Todos los cálculos son aproximaciones basadas en modelos simplificados y pueden no reflejar con exactitud tu situación crediticia real.</p>
                  <p>Los resultados del puntaje FICO generados por ScoreMotive son estimaciones educativas únicamente. Tu puntaje real puede variar significativamente dependiendo de múltiples factores evaluados directamente por las agencias de crédito (Experian, Equifax, TransUnion).</p>
                  <p>Antes de tomar decisiones financieras importantes, consulta siempre con un Planificador Financiero Certificado (CFP), un consejero de crédito acreditado u otro profesional financiero calificado.</p>
                </>
              ) : (
                <>
                  <p>ScoreMotive is an educational and informational tool designed to help users understand basic financial concepts such as FICO credit scoring and debt management strategies.</p>
                  <p><strong className="text-[#f0f2f7]">The information provided by this application does NOT constitute professional financial, legal, or tax advice.</strong> All calculations are approximations based on simplified models and may not accurately reflect your real credit situation.</p>
                  <p>FICO score results generated by ScoreMotive are educational estimates only. Your actual credit score may vary significantly depending on multiple factors evaluated directly by credit bureaus (Experian, Equifax, TransUnion).</p>
                  <p>Before making any important financial decisions, always consult with a Certified Financial Planner (CFP), an accredited credit counselor, or another qualified financial professional.</p>
                </>
              )}
            </div>
          </section>

          {/* Affiliate Disclosure */}
          <section className="bg-[#0d1220] border border-white/[0.07] rounded-2xl p-8">
            <h2 className="text-xl font-bold text-[#f0f2f7] mb-4">
              {isEs ? "Divulgación de Afiliados" : "Affiliate Disclosure"}
            </h2>
            <div className="space-y-4 text-sm text-[#8892a4] leading-relaxed">
              {isEs ? (
                <>
                  <p>ScoreMotive participa en programas de marketing de afiliados. Esto significa que podemos recibir compensación cuando haces clic en enlaces a productos o servicios financieros presentados en este sitio web y completas una acción calificada.</p>
                  <p>Esta compensación puede influir en qué productos presentamos y cómo se muestran, pero no afecta nuestra integridad editorial. Solo recomendamos productos y servicios que creemos pueden ser genuinamente útiles para nuestros usuarios.</p>
                  <p>Las relaciones de afiliados que podemos tener incluyen, entre otras, emisores de tarjetas de crédito, servicios de monitoreo de crédito, aplicaciones de finanzas personales y plataformas de educación financiera.</p>
                  <p>Todos los enlaces de afiliados están identificados donde sea posible. La presencia de un enlace de afiliado no implica respaldo del producto o servicio vinculado.</p>
                </>
              ) : (
                <>
                  <p>ScoreMotive participates in affiliate marketing programs. This means we may receive compensation when you click on links to financial products or services featured on this website and complete a qualifying action.</p>
                  <p>This compensation may influence which products we feature and how they are presented, but it does not affect our editorial integrity. We only recommend products and services we believe may be genuinely useful to our users.</p>
                  <p>Affiliate relationships we may have include, but are not limited to, credit card issuers, credit monitoring services, personal finance apps, and financial education platforms.</p>
                  <p>All affiliate links are identified where possible. The presence of an affiliate link does not imply endorsement of the linked product or service.</p>
                </>
              )}
            </div>
          </section>

          {/* Privacy Policy */}
          <section className="bg-[#0d1220] border border-white/[0.07] rounded-2xl p-8">
            <h2 className="text-xl font-bold text-[#f0f2f7] mb-6">
              {isEs ? "Política de Privacidad" : "Privacy Policy"}
            </h2>
            <div className="space-y-6">

              <div>
                <h3 className="text-sm font-bold text-[#4f7cff] mb-2 uppercase tracking-wide">
                  {isEs ? "Información que Recopilamos" : "Information We Collect"}
                </h3>
                <div className="space-y-3 text-sm text-[#8892a4] leading-relaxed">
                  {isEs ? (
                    <>
                      <p><strong className="text-[#f0f2f7]">Correos electrónicos:</strong> Cuando te suscribes a nuestro newsletter o lista de espera, recopilamos tu dirección de email. Esta información se almacena de forma segura a través de Beehiiv.</p>
                      <p><strong className="text-[#f0f2f7]">Datos de uso:</strong> Podemos recopilar datos analíticos anónimos sobre cómo los visitantes usan nuestro sitio. Estos datos son agregados y no identifican usuarios individuales.</p>
                      <p><strong className="text-[#f0f2f7]">Datos financieros:</strong> Cualquier dato financiero que ingreses en nuestras herramientas se procesa localmente en tu navegador y NO se almacena en nuestros servidores ni se transmite a terceros.</p>
                    </>
                  ) : (
                    <>
                      <p><strong className="text-[#f0f2f7]">Email addresses:</strong> When you subscribe to our newsletter or waitlist, we collect your email address stored securely through Beehiiv.</p>
                      <p><strong className="text-[#f0f2f7]">Usage data:</strong> We may collect anonymous analytics data about how visitors use our website. This data is aggregated and does not identify individual users.</p>
                      <p><strong className="text-[#f0f2f7]">Financial inputs:</strong> Any financial data you enter into our tools is processed locally in your browser and is NOT stored on our servers or transmitted to third parties.</p>
                    </>
                  )}
                </div>
              </div>

              <div>
                <h3 className="text-sm font-bold text-[#4f7cff] mb-2 uppercase tracking-wide">
                  {isEs ? "Cómo Usamos tu Información" : "How We Use Your Information"}
                </h3>
                <div className="space-y-2 text-sm text-[#8892a4] leading-relaxed">
                  <p>{isEs ? "Usamos tu email para enviar newsletters y contenido educativo al que te has suscrito. No vendemos tu información personal a terceros." : "We use your email address to send newsletters and educational content you have opted into. We do not sell your personal information to third parties."}</p>
                </div>
              </div>

              <div>
                <h3 className="text-sm font-bold text-[#4f7cff] mb-2 uppercase tracking-wide">
                  {isEs ? "Cookies y Seguimiento" : "Cookies & Tracking"}
                </h3>
                <p className="text-sm text-[#8892a4] leading-relaxed">
                  {isEs ? "Podemos usar cookies y tecnologías similares para mejorar tu experiencia de navegación y analizar el tráfico del sitio. Puedes controlar la configuración de cookies a través de las preferencias de tu navegador." : "We may use cookies and similar tracking technologies to improve your browsing experience and analyze site traffic. You can control cookie settings through your browser preferences."}
                </p>
              </div>

              <div>
                <h3 className="text-sm font-bold text-[#4f7cff] mb-2 uppercase tracking-wide">
                  {isEs ? "Servicios de Terceros" : "Third-Party Services"}
                </h3>
                <div className="space-y-2 text-sm text-[#8892a4] leading-relaxed">
                  <p>{isEs ? "Nuestro sitio utiliza los siguientes servicios de terceros:" : "Our website uses the following third-party services that may collect data:"}</p>
                  <ul className="list-disc list-inside space-y-1 ml-2">
                    <li>Beehiiv — {isEs ? "marketing por email y envío de newsletters" : "email marketing and newsletter delivery"}</li>
                    <li>Vercel — {isEs ? "alojamiento del sitio web y análisis" : "website hosting and analytics"}</li>
                    <li>Cloudflare — {isEs ? "servicios de DNS y seguridad" : "DNS and security services"}</li>
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="text-sm font-bold text-[#4f7cff] mb-2 uppercase tracking-wide">
                  {isEs ? "Tus Derechos" : "Your Rights"}
                </h3>
                <div className="space-y-2 text-sm text-[#8892a4] leading-relaxed">
                  <p>{isEs ? "Tienes derecho a acceder, corregir o eliminar tu información personal en cualquier momento. Para cancelar la suscripción al newsletter, usa el enlace de cancelación en cualquier email que te enviemos." : "You have the right to access, correct, or delete your personal information at any time. To unsubscribe from our newsletter, use the unsubscribe link in any email we send you."}</p>
                  <p>{isEs ? "Para solicitudes relacionadas con privacidad, contáctanos en" : "For privacy-related requests, contact us at"} <a href="mailto:legal@scoremotive.com" className="text-[#4f7cff] hover:underline">legal@scoremotive.com</a></p>
                </div>
              </div>

            </div>
          </section>

          {/* Terms of Use */}
          <section className="bg-[#0d1220] border border-white/[0.07] rounded-2xl p-8">
            <h2 className="text-xl font-bold text-[#f0f2f7] mb-4">
              {isEs ? "Términos de Uso" : "Terms of Use"}
            </h2>
            <div className="space-y-4 text-sm text-[#8892a4] leading-relaxed">
              {isEs ? (
                <>
                  <p>Al usar ScoreMotive, aceptas usar las herramientas y el contenido únicamente para fines personales y educativos. Aceptas no reproducir, distribuir ni explotar comercialmente ningún contenido de este sitio sin permiso escrito.</p>
                  <p>ScoreMotive se proporciona &quot;tal cual&quot; sin garantías de ningún tipo. No somos responsables de ninguna decisión financiera tomada basándose en información de este sitio.</p>
                </>
              ) : (
                <>
                  <p>By using ScoreMotive, you agree to use the tools and content solely for personal, educational purposes. You agree not to reproduce, distribute, or commercially exploit any content from this website without written permission.</p>
                  <p>ScoreMotive is provided &quot;as is&quot; without warranties of any kind. We are not liable for any financial decisions made based on information from this website.</p>
                </>
              )}
            </div>
          </section>

          {/* Contact */}
          <section className="text-center py-8">
            <p className="text-sm text-[#8892a4] mb-4">
              {isEs ? "¿Preguntas sobre nuestras políticas legales?" : "Questions about our legal policies?"}
            </p>
            <a href="mailto:legal@scoremotive.com" className="inline-flex items-center gap-2 bg-[rgba(79,124,255,0.1)] border border-[rgba(79,124,255,0.2)] text-[#7ba7ff] px-6 py-3 rounded-xl text-sm font-medium hover:bg-[rgba(79,124,255,0.15)] transition-all">
              legal@scoremotive.com
            </a>
          </section>

        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/[0.07] py-6 px-6 mt-8">
        <div className="max-w-4xl mx-auto flex items-center justify-between flex-wrap gap-4">
          <span className="text-xs text-[#8892a4]">© 2026 ScoreMotive · {isEs ? "Solo uso educativo" : "Educational use only"}</span>
          <div className="flex gap-6">
            <a href="/" className="text-xs text-[#8892a4] hover:text-[#f0f2f7] transition-colors">{isEs ? "Inicio" : "Home"}</a>
            <a href="/about" className="text-xs text-[#8892a4] hover:text-[#f0f2f7] transition-colors">{isEs ? "Nosotros" : "About"}</a>
            <a href="/tools" className="text-xs text-[#8892a4] hover:text-[#f0f2f7] transition-colors">{isEs ? "Herramientas" : "Tools"}</a>
          </div>
        </div>
      </footer>

    </main>
  );
}
